### PR TITLE
fix: error notification when running onboarding tours

### LINKED ISSUE #144: [BUG]: Tour yields two "unexpected error" notifications
### Description

When doing the tour, two "unexpected error" notifications happen

### Steps to Reproduce

1. start dev setup
```bash
git clone https://github.com/adfinis/timed
cd timed
make start
make keycloak-import
make loaddata
```
2. head to https://timed.local and log in (user doesn't matter)
3. Press continue/next buttons on tour
4. receive "unexpected error"

### Expected Behavior

No "unexpected error"

### Attachments

(in chronological order)

image
image
image
image
image

### Additional Context

_No response_

### Version

v4.0.1

### Required

- [X] I have checked past issues to see if this bug has already been reported.

### PR DESCRIPTION
**Pull request by MitanOmar**
fix #144

### CODE REVIEW

File: frontend/app/services/tour.js [hunk 1]
```diff
@@ -159,8 +159,8 @@ export default class TourService extends Tour {
               await this.router.transitionTo(
                 this.autostartTour.undoneTours.shift() ?? "index"
               );
-            } catch (error) {
-              this.notify.error("unexpected error");
+            } catch (_) {
+              _.toString();
             }
```
Comment (c0rydoras) [inline frontend/app/services/tour.js:164]: this:

1. doesn't fix the underlying issue
2. the `_.toString()` doesn't do anything and is not necessary

Since this is important for onboarding tho, we can probably use this as a **temporary** solution
```suggestion
            } catch {}
```

(i haven't tested the suggestion but it should be equivalent to the proposed **temporary** solution

**Review by c0rydoras — CHANGES_REQUESTED** [review]

File: frontend/app/services/tour.js (hunk 1 above)
Comment (c0rydoras) [reply frontend/app/services/tour.js:164]: i haven't done frontend in a while, you can probably just add a **temporary** eslint ignore comment

Comment (c0rydoras) [reply frontend/app/services/tour.js:164]: But yes, eslint is right, we shouldn't have empty block statements

Comment (c0rydoras) [reply frontend/app/services/tour.js:164]: AFAIK, especially in try catch statements, an empty (catch) block is an antipattern

Comment (c0rydoras) [reply frontend/app/services/tour.js:164]: @derrabauke what would you say?

Comment (derrabauke) [reply frontend/app/services/tour.js:164]: Why fix the symptom and not the root cause? @MitanOmar, why is the transition aborted in the first place?

Comment (MitanOmar) [reply frontend/app/services/tour.js:164]: @derrabauke i really don't know, but when i put `this.router.transitionTo` inside any try catch, even not there, it's throwing this error

Comment (MitanOmar) [reply frontend/app/services/tour.js:164]: @derrabauke for example, in the home page, i change the routing from
```hbs
          <LinkTo @route="index.attendances">
            Attendances
            <span class="badge">{{humanize-duration this.attendanceSum}}</span>
          </LinkTo>
```
to be an action in the controller with `this.router.transitionTo` with try catch, it was throwing the same error again

Comment (derrabauke) [reply frontend/app/services/tour.js:164]: I've checked it. Just remove the `try-catch` block. It's not necessary at this point.

Comment (MitanOmar) [reply frontend/app/services/tour.js]: @derrabauke done

Comment (derrabauke) [reply frontend/app/services/tour.js:164]: Sure you pushed the changes? O.o

Comment (MitanOmar) [reply frontend/app/services/tour.js:164]: yes, this is the final results :)

Comment (derrabauke) [reply frontend/app/services/tour.js:164]: image

the catch block has still some non-sense code in it. Would expect `catch {}` with some eslint exception comment in it!?

Comment (MitanOmar) [reply frontend/app/services/tour.js]: @derrabauke  it's empty now

**Review by derrabauke — APPROVED** [review]

File: frontend/app/services/tour.js [hunk 2]
```diff
@@ -159,8 +159,8 @@ export default class TourService extends Tour {
               await this.router.transitionTo(
                 this.autostartTour.undoneTours.shift() ?? "index"
               );
-            } catch (error) {
-              this.notify.error("unexpected error");
+            } catch {
+              /* tslint:disable:no-empty */
```
Comment (c0rydoras) [inline frontend/app/services/tour.js:163]: tslint? AFAIK we use eslint, and no typescript :c

Comment (MitanOmar) [reply frontend/app/services/tour.js]: changed, Thanks

Comment (derrabauke) [reply frontend/app/services/tour.js]: true dat.. `// eslint-disable-next-line no-empty`

**Review by c0rydoras — APPROVED** [review]

File: frontend/app/services/tour.js [hunk 3]
```diff
@@ -159,8 +159,8 @@ export default class TourService extends Tour {
               await this.router.transitionTo(
                 this.autostartTour.undoneTours.shift() ?? "index"
               );
-            } catch (error) {
-              this.notify.error("unexpected error");
+            } catch {
+              /* eslint:disable:no-empty */
```
Comment (derrabauke) [inline frontend/app/services/tour.js:163]:
```suggestion
              // eslint-disable-line no-empty
```
